<a href="https://colab.research.google.com/github/ayalarodrigues/residencia-ciberseguranca/blob/main/Exercicio_fixa%C3%A7%C3%A3o_transforma%C3%A7%C3%B5es_etl_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [7]:
df = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'CARLA', None],
    'idade': [25, None, 31, 40],
    'cidade': ['Fortaleza', 'fortaleza', 'Recife', ''],
    'valor_compra': ['120,50', '89,90', None, '210,00'],
               'data': ['2026-03-01', '01/03/2026', '2026/03/02', None]

})

print(df)

  cliente  idade     cidade valor_compra        data
0     Ana   25.0  Fortaleza       120,50  2026-03-01
1   Bruno    NaN  fortaleza        89,90  01/03/2026
2   CARLA   31.0     Recife         None  2026/03/02
3    None   40.0                  210,00        None

Exercício de fixação

1. Quais colunas têm maior risco de erro;

**R: As colunas com maior risco de erro são 'cliente, 'cidade', 'valor_compra' e 'data', pois elas não estão padronizadas, possuem valores ausentes, formatos diferentes  e campos vazios. A coluna idade também precisa de atenção por possuir valor nulo.**

2. Onde faz sentido preencher nulos;

**R: Faz sentido preencher nulos principalmente em 'idade', usando média ou mediana. Também pode ser adequado preencher 'cliente' e 'cidade' com algum valor padrão, como 'Desconhecido'ou 'Não informado'. Já em 'data' e 'valor_compra', o preenchimento é mais complicado porque envolve dados mais sensíveis.**

3. Onde faz sentido remover registros.

**R: Faz sentido remover registros principalmente quando faltam dados importantes, como 'valor_compra' e 'data'. Registros também podem ser removidos caso existam muitos erros. Porém, alguns nulos podem ser tratados sem a exclusão do registro, como acontece em 'idade'.**

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cliente       3 non-null      object
 1   idade         3 non-null      float64
 2   cidade        4 non-null      object
 3   valor_compra  3 non-null      object
 4   data          3 non-null      object
dtypes: float64(1), object(4)
memory usage: 292.0+ bytes

In [8]:
#Verifica valores vazios em cidade

print(df['cidade'] == "")

0    False
1    False
2    False
3     True
Name: cidade, dtype: bool

In [10]:
#Preenchimento de nulos

#Preenche idade com mediana

df["idade"] = df["idade"].fillna(df["idade"].median())
df

  cliente  idade     cidade valor_compra        data
0     Ana   25.0  Fortaleza       120,50  2026-03-01
1   Bruno   31.0  fortaleza        89,90  01/03/2026
2   CARLA   31.0     Recife         None  2026/03/02
3    None   40.0                  210,00        None

In [11]:
#Preenche cliente com um texto padrão

df["cliente"] = df["cliente"].fillna("Desconhecido")
df

        cliente  idade     cidade valor_compra        data
0           Ana   25.0  Fortaleza       120,50  2026-03-01
1         Bruno   31.0  fortaleza        89,90  01/03/2026
2         CARLA   31.0     Recife         None  2026/03/02
3  Desconhecido   40.0                  210,00        None

In [14]:
# Preenche cidade vazia com 'Não informado"

df["cidade"] = df["cidade"].replace("", "Não informado")
df

        cliente  idade         cidade valor_compra        data
0           Ana   25.0      Fortaleza       120,50  2026-03-01
1         Bruno   31.0      Fortaleza        89,90  01/03/2026
2         Carla   31.0         Recife         None  2026/03/02
3  Desconhecido   40.0  Não informado       210,00        None

In [15]:
# Padronização de nomes dos clientes

#Coloca a primeira letra da cada palavra em maiúscula e o resto em minúscula

df["cliente"] = df["cliente"].str.title()
df

        cliente  idade         cidade valor_compra        data
0           Ana   25.0      Fortaleza       120,50  2026-03-01
1         Bruno   31.0      Fortaleza        89,90  01/03/2026
2         Carla   31.0         Recife         None  2026/03/02
3  Desconhecido   40.0  Não informado       210,00        None

In [16]:
# Padronização de cidades

df["cidade"] = df["cidade"].str.title()
df

        cliente  idade         cidade valor_compra        data
0           Ana   25.0      Fortaleza       120,50  2026-03-01
1         Bruno   31.0      Fortaleza        89,90  01/03/2026
2         Carla   31.0         Recife         None  2026/03/02
3  Desconhecido   40.0  Não Informado       210,00        None

In [17]:
# Converter 'valor_compra' para número

df["valor_compra"] = df["valor_compra"].str.replace(",", ".", regex=False) #troca a vírgula por ponto
df["valor_compra"] = pd.to_numeric(df["valor_compra"], errors="coerce") # 'coerce' transforma inválido em nulo

df['valor_compra']

0    120.5
1     89.9
2      NaN
3    210.0
Name: valor_compra, dtype: float64

In [18]:
#Converte 'data' para formato de data

df["data"] = pd.to_datetime(df["data"], errors="coerce", dayfirst=True)
df["data"]

0   2026-01-03
1          NaT
2          NaT
3          NaT
Name: data, dtype: datetime64[ns]

In [19]:
#Remove registros com 'valor_compra' nulo

df_sem_valor_nulo = df.dropna(subset=["valor_compra"])
df_sem_valor_nulo

        cliente  idade         cidade  valor_compra       data
0           Ana   25.0      Fortaleza         120.5 2026-01-03
1         Bruno   31.0      Fortaleza          89.9        NaT
3  Desconhecido   40.0  Não Informado         210.0        NaT